name = "dependent-computability"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["DependentComputability"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4-nightly-testing"
rev = "477d626d6db87271dac80af33ce9a91071d00bee"

[[lean_lib]]
name = "DependentComputability"
